export const posts = [
  {
    id: 1,
    fullname: "Raunak Tibrewal",
    userName: "@raunaktibrewal",
    description:
      "Getting my first covid vaccine.Getting my first covid vaccine.Getting my first covid vaccine",
    likes: 100,
    comments: 50,
    retweet: 2,
    share: 10,
    createdDate: "Wed Jun 02 2021 23:11:51 GMT+0530 (India Standard Time)",
    attachment: [],
  },
  {
    id: 2,
    fullname: "Ritesh Mukim",
    userName: "@riteshmukim",
    description: "Getting my first covid vaccine",
    likes: 100,
    comments: 50,
    retweet: 2,
    share: 10,
    createdDate: "Wed Jun 02 2021 23:11:51 GMT+0530 (India Standard Time)",
    attachment: [],
  },
  {
    id: 3,
    fullname: "Nitesh Nahata",
    userName: "@niteshnahata",
    description: "Getting my first covid vaccine",
    likes: 100,
    comments: 50,
    retweet: 2,
    share: 10,
    createdDate: "Wed Jun 02 2021 23:11:51 GMT+0530 (India Standard Time)",
    attachment: [],
  },
  {
    id: 4,
    fullname: "Rohan Gupta",
    userName: "@rohangupta",
    description:
      "Getting my first covid vaccine.Getting my first covid vaccine.Getting my first covid vaccine",
    likes: 100,
    comments: 50,
    retweet: 2,
    share: 10,
    createdDate: "Wed Jun 02 2021 23:11:51 GMT+0530 (India Standard Time)",
    attachment: [],
  },
  {
    id: 5,
    fullname: "Rohan Gupta",
    userName: "@rohangupta",
    description:
      "Getting my first covid vaccine.Getting my first covid vaccine.Getting my first covid vaccine",
    likes: 100,
    comments: 50,
    retweet: 2,
    share: 10,
    createdDate: "Wed Jun 02 2021 23:11:51 GMT+0530 (India Standard Time)",
    attachment: [],
  },
  {
    id: 6,
    fullname: "Rohan Gupta",
    userName: "@rohangupta",
    description:
      "Getting my first covid vaccine.Getting my first covid vaccine.Getting my first covid vaccine",
    likes: 100,
    comments: 50,
    retweet: 2,
    share: 10,
    createdDate: "Wed Jun 02 2021 23:11:51 GMT+0530 (India Standard Time)",
    attachment: [],
  },
  {
    id: 7,
    fullname: "Rohan Gupta",
    userName: "@rohangupta",
    description:
      "Getting my first covid vaccine.Getting my first covid vaccine.Getting my first covid vaccine",
    likes: 100,
    comments: 50,
    retweet: 2,
    share: 10,
    createdDate: "Wed Jun 02 2021 23:11:51 GMT+0530 (India Standard Time)",
    attachment: [],
  },
  {
    id: 8,
    fullname: "Rohan Gupta",
    userName: "@rohangupta",
    description:
      "Getting my first covid vaccine.Getting my first covid vaccine.Getting my first covid vaccine",
    likes: 100,
    comments: 50,
    retweet: 2,
    share: 10,
    createdDate: "Wed Jun 02 2021 23:11:51 GMT+0530 (India Standard Time)",
    attachment: [],
  },
];

//API Key-UyAOkgwbzVpAGJv4xRhdlQZ5R
//API Secret Key - yr7V870sva8ePII60z5VY2hqByznQWUTkUPlo6yi7ZUPl6oADJ
//Bearer Token -AAAAAAAAAAAAAAAAAAAAAAAZQQEAAAAA%2FuR9OSQpuCt3kthlm%2BzjKiCMX%2F8%3D7zJf0pPwK5MQz0SZD2PxV1OI2hF3oXST33oLU5gqpFoCtQxKZ0
